CREATE TABLE [Globalization].[Languages]
(
	[Guid]			UNIQUEIDENTIFIER	NOT NULL,
	[Alias]			NVARCHAR(10)		NULL,
	[TitleRu]		NVARCHAR(50)		NULL,
	[TitleEn]		NVARCHAR(50)		NULL,
	[Description]	NVARCHAR(1024)		NULL,
	[IsDeleted]		BIT					NOT NULL DEFAULT 0,

	CONSTRAINT [PK_Languages] PRIMARY KEY CLUSTERED ([GUID] ASC)
)